# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.srcs/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1.xci
# IP: The module: 'mbblockdesign_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.srcs/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1.xci
# IP: The module: 'mbblockdesign_clk_wiz_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /1work/fpgaproc/pf_base_mb_bm_min/pf_base_mb_bm_min.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_clk_wiz_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
