# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.srcs/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0.xci
# IP: The module: 'mbblockdesign_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.srcs/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0.xci
# IP: The module: 'mbblockdesign_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
