# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.srcs/sources_1/bd/mbblockdesign/ip/mbblockdesign_xbar_0/mbblockdesign_xbar_0.xci
# IP: The module: 'mbblockdesign_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_xbar_0/mbblockdesign_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.srcs/sources_1/bd/mbblockdesign/ip/mbblockdesign_xbar_0/mbblockdesign_xbar_0.xci
# IP: The module: 'mbblockdesign_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/ip/mbblockdesign_xbar_0/mbblockdesign_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mbblockdesign_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
