# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/pf_base_mb_bm_min_given/Arty-A7-100-Master.xdc

# Block Designs: bd/mbblockdesign/mbblockdesign.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign || ORIG_REF_NAME==mbblockdesign} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_clk_wiz_0_1/mbblockdesign_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_clk_wiz_0_1 || ORIG_REF_NAME==mbblockdesign_clk_wiz_0_1} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_util_vector_logic_0_0/mbblockdesign_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_util_vector_logic_0_0 || ORIG_REF_NAME==mbblockdesign_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_microblaze_0_0/mbblockdesign_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_microblaze_0_0 || ORIG_REF_NAME==mbblockdesign_microblaze_0_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_dlmb_v10_0/mbblockdesign_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_dlmb_v10_0 || ORIG_REF_NAME==mbblockdesign_dlmb_v10_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_ilmb_v10_0/mbblockdesign_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_ilmb_v10_0 || ORIG_REF_NAME==mbblockdesign_ilmb_v10_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_dlmb_bram_if_cntlr_0/mbblockdesign_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbblockdesign_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_ilmb_bram_if_cntlr_0/mbblockdesign_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mbblockdesign_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_lmb_bram_0/mbblockdesign_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_lmb_bram_0 || ORIG_REF_NAME==mbblockdesign_lmb_bram_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_xbar_0/mbblockdesign_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_xbar_0 || ORIG_REF_NAME==mbblockdesign_xbar_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_microblaze_0_axi_periph_0/mbblockdesign_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mbblockdesign_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_microblaze_0_axi_intc_0/mbblockdesign_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_microblaze_0_axi_intc_0 || ORIG_REF_NAME==mbblockdesign_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_microblaze_0_xlconcat_0/mbblockdesign_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_microblaze_0_xlconcat_0 || ORIG_REF_NAME==mbblockdesign_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_mdm_1_0/mbblockdesign_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_mdm_1_0 || ORIG_REF_NAME==mbblockdesign_mdm_1_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_rst_clk_wiz_0_100M_0/mbblockdesign_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==mbblockdesign_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_axi_uartlite_0_0/mbblockdesign_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_axi_uartlite_0_0 || ORIG_REF_NAME==mbblockdesign_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_axi_gpio_0_0/mbblockdesign_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_axi_gpio_0_0 || ORIG_REF_NAME==mbblockdesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_axi_timer_0_0/mbblockdesign_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_axi_timer_0_0 || ORIG_REF_NAME==mbblockdesign_axi_timer_0_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_xlconstant_0_0/mbblockdesign_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_xlconstant_0_0 || ORIG_REF_NAME==mbblockdesign_xlconstant_0_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_axi_uartlite_1_0/mbblockdesign_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_axi_uartlite_1_0 || ORIG_REF_NAME==mbblockdesign_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/mbblockdesign/ip/mbblockdesign_axi_gpio_1_0/mbblockdesign_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mbblockdesign_axi_gpio_1_0 || ORIG_REF_NAME==mbblockdesign_axi_gpio_1_0} -quiet] -quiet

# XDC: /1work/fpgaproc/test_mb_pmod_maxsonar/test_mb_pmod_maxsonar.gen/sources_1/bd/mbblockdesign/mbblockdesign_ooc.xdc
