domain_path: /1work/fpgaproc/test_mb_pmod_clp_sw/platform/export/platform/sw/standalone_microblaze_0
app_src_dir: /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
template: hello_world
