paths:
  /opt/xilinx/Vitis/2023.2/data/embeddedsw: {}
os:
  standalone:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/bsp/standalone_v9_0
  freertos10_xilinx:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/ThirdParty/bsp/freertos10_xilinx_v1_14
driver:
  emc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/emc_v4_2
  can:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/can_v3_7
  xxvethernet:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/xxvethernet_v1_8
  dfeofdm:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dfeofdm_v1_1
  canfd:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/canfd_v2_8
  intc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/intc_v3_17
  uartlite:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/uartlite_v3_9
  rfdc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/rfdc_v12_1
  axicdma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/axicdma_v4_12
  axidma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/axidma_v9_17
  bram:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/bram_v4_9
  dfeprach:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dfeprach_v1_6
  gpio:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/gpio_v4_10
  pciepsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/pciepsu_v1_6
  v_frmbuf_rd:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/v_frmbuf_rd_v4_7
  canps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/canps_v3_7
  sysmon:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/sysmon_v7_8
  dfemix:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dfemix_v1_6
  csudma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/csudma_v1_14
  mbox:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/mbox_v4_6
  v_frmbuf_wr:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/v_frmbuf_wr_v4_7
  ipipsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/ipipsu_v2_14
  iic:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/iic_v3_10
  llfifo:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/llfifo_v5_5
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/llfifo_v5_6
  dmaps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dmaps_v2_9
  trafgen:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/trafgen_v4_5
  vtc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/vtc_v8_5
  scugic:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/scugic_v5_2
  ddrcpsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/ddrcpsu_v1_5
  aienginev2:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/aienginev2_v3_4
  spi:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/spi_v4_11
  mutex:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/mutex_v4_7
  uartns550:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/uartns550_v3_9
  xdmapcie:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/xdmapcie_v1_7
  clk_wiz:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/clk_wiz_v1_6
  sd_fec:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/sd_fec_v1_3
  common:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/common_v1_3
  wdtps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/wdtps_v3_6
  avbuf:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/avbuf_v2_6
  dpdma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dpdma_v1_5
  ttcps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/ttcps_v3_18
  trngpsv:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/trngpsv_v1_4
  axiethernet:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/axiethernet_v5_16
  usbps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/usbps_v2_8
  dfeequ:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dfeequ_v1_5
  zdma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/zdma_v1_17
  spips:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/spips_v3_9
  dppsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dppsu_v1_7
  nandpsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/nandpsu_v1_12
  devcfg:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/devcfg_v3_8
  emacps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/emacps_v3_19
  prd:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/prd_v2_2
  xadcps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/xadcps_v2_7
  sysmonpsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/sysmonpsu_v2_9
  uartpsv:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/uartpsv_v1_9
  v_tpg:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/v_tpg_v8_5
  cframe:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/cframe_v1_5
  usbpsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/usbpsu_v1_14
  sysmonpsv:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/sysmonpsv_v4_1
  iomodule:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/iomodule_v2_15
  resetps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/resetps_v1_6
  qspipsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/qspipsu_v1_18
  prc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/prc_v2_2
  iicps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/iicps_v3_18
  axipmon:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/axipmon_v6_10
  video_common:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/video_common_v4_14
  nandps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/nandps_v2_8
  ospipsv:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/ospipsv_v1_9
  cfupmc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/cfupmc_v1_6
  rtcpsu:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/rtcpsu_v1_13
  mcdma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/mcdma_v1_9
  emaclite:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/emaclite_v4_8
  dfxasm:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dfxasm_v1_2
  tmr_inject:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/tmr_inject_v1_6
  clockps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/clockps_v1_5
  tmrctr:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/tmrctr_v4_11
  gpiops:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/gpiops_v3_12
  trngpsx:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/trngpsx_v1_1
  dfeccf:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/dfeccf_v1_6
  tft:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/tft_v6_4
  tmr_manager:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/tmr_manager_v1_5
  wdttb:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/wdttb_v5_7
  axivdma:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/axivdma_v6_14
  qspips:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/qspips_v3_11
  sdps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/sdps_v4_2
  hwicap:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/hwicap_v11_6
  usb:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/usb_v5_6
  uartps:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/uartps_v3_13
  coresightps_dcc:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/coresightps_dcc_v1_9
  scutimer:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/scutimer_v2_5
  scuwdt:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/scuwdt_v2_5
  axis_switch:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/XilinxProcessorIPLib/drivers/axis_switch_v1_6
library:
  xilmailbox:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilmailbox_v1_8
  xilpuf:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilpuf_v2_2
  xilffs:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilffs_v5_1
  xilplmi:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilplmi_v1_9
  xilrsa:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilrsa_v1_7
  xilloader:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilloader_v1_9
  xilpm:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilpm_v5_1
  xilsem:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilsem_v1_8
  xilskey:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilskey_v7_5
  xiltimer:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xiltimer_v1_3
  xilpdi:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilpdi_v1_8
  xilnvm:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilnvm_v3_2
  xilsecure:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilsecure_v5_2
  xilfpga:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilfpga_v6_5
  xilflash:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_services/xilflash_v4_10
  libmetal:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/ThirdParty/sw_services/libmetal_v2_6
  openamp:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/ThirdParty/sw_services/openamp_v1_9
  lwip213:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/ThirdParty/sw_services/lwip213_v1_1
apps:
  zynqmp_fsbl:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
  zynqmp_dram_test:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynqmp_dram_test
  peripheral_tests:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/peripheral_tests
  lwip_tcp_perf_client:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/lwip_tcp_perf_client
  libmetal_echo_demo:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/libmetal_echo_demo
  dhrystone:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/dhrystone
  lwip_echo_server:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/lwip_echo_server
  openamp_echo_test:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/openamp_echo_test
  rsa_auth_app:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/rsa_auth_app
  freertos_lwip_udp_perf_client:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/freertos_lwip_udp_perf_client
  freertos_lwip_tcp_perf_server:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/freertos_lwip_tcp_perf_server
  lwip_tcp_perf_server:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/lwip_tcp_perf_server
  zynq_dram_test:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynq_dram_test
  lwip_udp_perf_server:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/lwip_udp_perf_server
  zynqmp_pmufw:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynqmp_pmufw
  empty_application:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/empty_application
  zynq_fsbl:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/zynq_fsbl
  freertos_lwip_echo_server:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/freertos_lwip_echo_server
  openamp_rpc_demo:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/openamp_rpc_demo
  lwip_udp_perf_client:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/lwip_udp_perf_client
  freertos_lwip_tcp_perf_client:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/freertos_lwip_tcp_perf_client
  srec_bootloader:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/srec_bootloader
  memory_tests:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/memory_tests
  srec_spi_bootloader:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/srec_spi_bootloader
  openamp_matrix_multiply:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/openamp_matrix_multiply
  ddr_self_refresh:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/ddr_self_refresh
  hello_world:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/hello_world
  freertos_lwip_udp_perf_server:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/freertos_lwip_udp_perf_server
  versal_plm:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/versal_plm
  versal_psmfw:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/versal_psmfw
  freertos_hello_world:
    path:
    - /opt/xilinx/Vitis/2023.2/data/embeddedsw/lib/sw_apps/freertos_hello_world
